language: node_js
node_js:
  - 7.9.0
branches:
  only:
    - master
env:
  global:
    - secure: "dC6m+0cx5uUkX4l89kPiDDRVAqFMeD7/UOdlp29B75Y7wCLac+bu2vobpXd2lJj1WCTWC3FIKHKGFmNxsoxV1W0krZJxq9CXjVncgoShSpF6UfXIb7iJYAnOw8jtf2YZT85zOukbo85we7F+G+bDq7C0/pH0j1vfCXbsWwU45bgAWd3kxuCOTOhcrZDN6ajpUGAhFqtj05Y5g9YH/0RNCC/RcRD4uka9h3rGgXnG9NhrGAuFR2S6FQwt4C7JrS1mX9SKkJZg8Rxqrn5g+ejusKV/18zqIZY8/mcBZ6GxGuLb9NshEDOsjWWcCxaJ9LVQgWQntT8TQG90CzKCu9RS2+i76oMH3sJ/ofQwDbLU85ioMx7aCA3J7dfYsjOK4wmklKT81T6DxYzEcuNd+uSfUwSkcJYCsXzMH04ogyCymIcvTm2GcA3C/Uc2sY2zfFLk5b4NWVfFQAicNlr8e2QoqsAj6mHIGZ+0pwClrrag4X1VimkDI3fx2NGDRoHFKXk1pWF/L9WVURxJIshTLb6I5fa0upDuGNiXIvwGBUM/nDhasplCVasSvr8ilChdv7VlmvqVmuFMtFQddUPuzEL+6KsGsas/Wd+WWAnaYcElj0/qCOR/ffzX2rPDkdqePirU5mPQJTTntKBBRW1sIXSCQOV6QaQT5GwT8Rx2mSRX6+g="

script:
  - yarn global add git-credential-env
  - git config credential.helper "env --username=TRAVIS_GITHUB_TOKEN"
  - git config user.name "Travis CI"
  - git config user.email "builds@travis-ci.org"
  - yarn run deploy
